# Generated by Django 3.0.8 on 2020-10-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201029_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_comment',
            field=models.TextField(null=True),
        ),
    ]
