# Generated by Django 3.0.8 on 2021-01-26 14:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_auto_20210126_2025'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follow',
            new_name='FollowModel',
        ),
    ]
