# Generated by Django 3.0.8 on 2021-03-17 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_auto_20210317_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='commented',
            field=models.ManyToManyField(blank=True, default=None, related_name='commented', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='liked',
            field=models.ManyToManyField(blank=True, default=None, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
